slack:
  webhook: https://hooks.slack.com/services/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
  application:
    client-id: 1407680307520.1906499659744
    client-secret: 657aecd91f617ba6f9f75ccc235a41eb
    signing: 6e2051a684fd1b7de55a798256424ac3

spring:
  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: admin
    host: rattlesnake.rmq.cloudamqp.com
    username: lmmgtdet
    password: UDlz-IlIELwOH5nLssBj6rx7JtrSWubH
    virtualhost: lmmgtdet
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: adcr.fiap@gmail.com
    password: Fg4Bq5O$s6ZE
    port: 587
    subject: Dados da intensao
    to: adcr.fiap@gmail.com
    from: adcr.fiap@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: dkchevis@gmail.com
#    password: <>
#    port: 587
#    subject: Intensao de compra
#    to: dkchevi@hotmail.com
#    from: dkchevis@gmail.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
    protocol: smtp
    test-connection: false



